# Uninstall common requirements for all playbooks
- name: Remove app/bin directory if it exists
  ansible.builtin.file:
    path: "{{ app_directory }}/bin"
    state: absent
- name: Remove app directory if it exists
  ansible.builtin.file:
    path: "{{ app_directory }}"
    state: absent
- name: Remove install directory
  ansible.builtin.file:
    path: "{{ install_directory }}"
    state: absent
- name: Remove Python3.12 venv
  ansible.builtin.apt:
    name: python3.12-venv
    state: absent
    update_cache: false
  become: true
