- name: Install Python Requirements
  hosts: core
  become: true
  tasks:
    - name: Update apt cache if stale
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
    - name: Upgrade all packages to their latest version
      ansible.builtin.apt:
        upgrade: dist
        update_cache: false
    - name: Install openJDK 21 for Kafka
      ansible.builtin.apt:
        name: openjdk-21-jre-headless
        state: present
        update_cache: false
    - name: Install Python3.12
      ansible.builtin.apt:
        name: python3.12
        state: present
        update_cache: false
    - name: Install Python3.12 venv
      ansible.builtin.apt:
        name: python3.12-venv
        state: present
        update_cache: false
    - name: Install VLC Media Player
      ansible.builtin.apt:
        name: vlc
        state: present
        update_cache: false
