- name: Deploy Rupert Virtual Environment, Config, and Control Script
  hosts: core
  tasks:
    - name: Install rupert python dependencies in a virtual environment
      ansible.builtin.pip:
        name:
          - "beartype=={{ beartype_version }}"
          - "confluent_kafka=={{ confluent_kafka_version }}"
          - "flask=={{ flask_version }}"
          - "tinytuya=={{ tinytuya_version }}"
          - "python-vlc=={{ python_vlc_version }}"
        virtualenv: "{{ app_directory }}/rupert_venv-{{ rupert_venv_version }}"
        virtualenv_command: /usr/bin/python3 -m venv
    - name: Create a link to the rupert venv
      ansible.builtin.file:
        src: "{{ app_directory }}/rupert_venv-{{ rupert_venv_version }}"
        dest: "{{ app_directory }}/rupert_venv"
        state: link
      when: not ansible_check_mode # Check will fail if Rupert venv has not already been deployed